version: 0.1

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"

phases:
  install:
    commands:
    - echo installing maven...
    - sudo yum update -y
    - sudo yum install -y java-11-amazon-corretto
    - sudo yum install -y maven
  build:
    commands:
    - echo build the app
    - mvn install
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'

