version: 0.1

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/openjdk-11-jdk"

phases:
  install:
    commands:
    - echo installing maven...
    - sudo apt-get update
    - sudo apt-get install openjdk-11-jdk
    - sudo apt-get install maven
  build:
    commands:
    - echo build the app
    - mvn install
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'

