version: 0.1

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/openjdk-11-jdk"

phases:
  install:
    commands:
    - echo installing maven...
    - sudo apt-get update
    - sudo apt-get install -y openjdk-11-jdk
    - sudo apt-get install -y maven
  build:
    commands:
    - echo build the app
    - mvn install -Dmaven.test.skip=true
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'

